// react-ui-app/src/components/App.js
import React, { Component } from "react";
import { accountSelector, contractsLoadedSelector } from "../store/selectors";
import { connect } from "react-redux";
import { loadWeb3, loadAccount, loadMarketplace } from "../store/interactions";
import "./App.css";
import Navbar from "./Navbar";
import Content from "./Content";
// TODO : look lesson 17 and setup truffle-config to put build to ./src directory

const ipfsClient = require("ipfs-http-client");
const ipfs = require("ipfs-http-client")({
  host: "ipfs.infura.io",
  port: "5001",
  protocol: "https",
});
const axios = require("axios");

class App extends Component {
  async componentWillMount() {
    await this.loadBlockchainData(this.props.dispatch);

    // await this.createTicket("123", 8, 3);
    // await this.initMarketplace();
  }

  async initMarketplace() {
    this.state.myTickets = [];
    this.state.items = [];

    const num_tickets = await this.contract.methods.getOnSaleLength().call();
    // console.log("!!!!!num_tickets", num_tickets);
    var uri, data, item, myTicket, onSale, owner;
    for (let i = 0; i < num_tickets; i++) {
      onSale = await this.contract.methods.onSale(i).call();
      owner = await this.contract.methods.owners(i).call();
      //if (owner == this.account) this.myTickets.push(i);
      uri = await this.contract.methods.tokenURI(i).call();
      try {
        data = await axios.get(uri);
        if (owner == this.account) {
          myTicket = data.data;
          myTicket.ticket_id = i;
          myTicket.on_sale = await this.contract.methods.onSale(i).call();
          this.state.myTickets.push(myTicket);
        } else {
          item = data.data;
          item.ticket_id = i;
          item.on_sale = await this.contract.methods.onSale(i).call();
          console.log(item);
          this.state.items.push(item);
        }
      } catch (error) {
        console.log(error);
      }
    }
    console.log("!!!!!this.state.myTickets", this.state.myTickets);
  }

  async createTicket(price, seat, category) {
    let metadata = {
      seat_number: seat,
      ticket_category: category,
      ticket_value: price,
    };
    console.log(JSON.stringify(metadata));
    let result = await ipfs.add(JSON.stringify(metadata));

    console.log("IPFS hash: ", result.path);
    await this.contract.methods
      .createTicket(this.web3.utils.toWei(price, "ether"), result.path)
      .send({ from: this.account });
    console.log("Ticket created successfully!");

    const num_tickets = await this.contract.methods.getOnSaleLength().call();
    console.log("!!!!!num_tickets", num_tickets);
  }

  async loadBlockchainData(dispatch) {
    const web3 = await loadWeb3(dispatch);
    await loadAccount(web3, dispatch);
    const networkId = await web3.eth.net.getId();
    const marketplace = await loadMarketplace(web3, networkId, dispatch);
    if (!marketplace) {
      window.alert(
        "Marketplace smart contract not detected on the current network. Please select another network with Metamask."
      );
      return;
    }
  }

  render() {
    return (
      <div>
        <Navbar />

        {this.props.contractsLoaded ? (
          <Content />
        ) : (
          <div className="content"></div>
        )}
      </div>
    );
  }
}

function mapStateToProps(state) {
  return {
    account: accountSelector(state),
    contractsLoaded: contractsLoadedSelector(state),
  };
}

// export default App;
export default connect(mapStateToProps)(App);

// app/src/App.vue
<template>
  <v-app>
    <v-card>
      <v-card-title>
        <h3>Address: {{account}}</h3>
      </v-card-title>
      <v-divider></v-divider>
      <v-card-actions>
        <v-btn v-on:click="registerDialog=true" color="success">Register</v-btn>
        <v-spacer></v-spacer>
        <v-btn v-on:click="loginDialog=true" color="info">Login</v-btn>
      </v-card-actions>
    </v-card>
    <v-dialog v-model="registerDialog">
      <v-card>
        <v-card-title>
          <h3>Please fill in your personal details to register</h3>
        </v-card-title>
        <v-card-text>
          <v-form>
            <v-text-field label="Full Name"/>
            <v-text-field label="Date of Birth"/>
            <v-text-field label="Email Address"/>
          </v-form>
        </v-card-text>
        <v-divider></v-divider>
        <v-card-actions>
          <v-btn>Submit</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
    <v-dialog v-model="loginDialog">
      <v-card>
        <v-card-title>
          <h3>Enter your credentials to login</h3>
        </v-card-title>
        <v-card-text>
          <v-form>
            <v-text-field label="Username" prepend-icon="mdi-account-circle"/>
            <v-text-field type="Password" label="Password" prepend-icon="mdi-lock" append-icon="mdi-eye-off"/>
          </v-form>
        </v-card-text>
        <v-divider></v-divider>
        <v-card-actions>
          <v-btn>Submit</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
    <v-data-table :headers="headers" :items="items"></v-data-table>
    <v-card>
      <v-card-title>
        <h1>Create Tickets</h1>
      </v-card-title>
      <v-card-actions>
        <v-text-field v-model="seat" label="Define Seat Number"></v-text-field>
        <v-select v-model="category" :items="categories" label="Select Category"></v-select>
      </v-card-actions>
      <v-card-actions>
        <v-text-field v-model="price" label="Define Price (in ETH)"></v-text-field>
        <v-btn v-on:click="createTicket(price, seat, category)" color="blue">Mint</v-btn>
      </v-card-actions>
    </v-card>
    <v-card>
      <v-card-title>
        <h1>Change Ticket Price</h1>
      </v-card-title>
      <v-card-actions>
        <v-select v-model="ticketPriceID" :items="myTickets" label="Select Ticket ID"></v-select>
        <v-text-field v-model="price" label="Define Price (in ETH)"></v-text-field>
        <v-btn v-on:click="changeTicketPrice(ticketPriceID, price)" color="blue">Update</v-btn>
      </v-card-actions>
    </v-card>
    <v-card>
      <v-card-title>
        <h1>Toggle State</h1>
      </v-card-title>
      <v-card-actions>
        <v-select v-model="toggleID" :items="myTickets" label="Select Ticket ID"></v-select>
        <v-btn v-on:click="toggleSale(toggleID)" color="green">Toggle</v-btn>
      </v-card-actions>
    </v-card>
    <v-card>
      <v-card-title>
        <h1>Purchase Tickets</h1>
      </v-card-title>
      <v-card-actions>
        <v-select v-model="ticketID" :items="ticketsOnSale" label="Select Ticket ID"></v-select>
        <v-btn v-on:click="buyTicket(ticketID)" color="purple">Buy</v-btn>
      </v-card-actions>
    </v-card>
  </v-app>
</template>

<script language="javascript" type="text/javascript" src="jslibs/web3.min.js"></script>
<script>

import MarketplaceABI from './plugins/Marketplace';

const Web3 = require('web3');
const axios = require('axios');
const ipfsClient = require('ipfs-http-client');
const ipfs = ipfsClient({ host: 'ipfs.infura.io', port: '5001', protocol: 'https' });

export default {
  name: 'App',
  data () {
    return {
      web3Provider: null,
      contract: null,
      account: '0x0',
      categories: ['Normal', 'VIP'],
      category: '',
      seat: '',
      price: '',
      myTickets: [],
      toggleID: '',
      ticketsOnSale: [],
      ticketID: '',
      ticketPriceID: '',
      registerDialog: false,
      loginDialog: false,
      headers: [{ text: 'Seat Number', value: 'seat_number' },
                { text: 'Ticket Price (in ETH)', value: 'ticket_value' },
                { text: 'Category', value: 'ticket_category' },
                { text: 'Ticket ID', value: 'ticket_id'},
                { text: 'On Sale', value: 'on_sale'}],
      items: []
    }
  },

  async mounted() {
    await this.initProvider();
    await this.initContract();
    await this.initMarketplace();
  },

  methods: {
    async initProvider() {
      if (window.ethereum) {
        this.web3Provider = window.ethereum;
        web3 = new Web3(window.ethereum); //force it to version 1.2.8
        console.log("Current web3 version:",web3.version);
        let accounts = await web3.eth.getAccounts();
        this.account = accounts[0];
        console.log("Current connected account:",this.account);
      } else {
        console.log("Please install Metamask to continue.");
      }

      setInterval(async() => {
        //check whether account is changed at every one second interval
        let updated;
        updated = await web3.eth.getAccounts();
        if (updated[0] !== this.account) {
          this.account = updated[0];
          this.initMarketplace();
          // Call a function to update the UI with the new account
          alert("You changed account!");
        }
      }, 1000);
    },

    async initContract() {
      const contractAddress = "0xa029C3a51e202a0A2Ab793fF480B90eB91887a42"; //Mumbai testnet address
      this.contract = await new web3.eth.Contract(MarketplaceABI, contractAddress);
      console.log(this.account);
      var self = this;
      this.contract.events.saleToggled().on('data', function(event){
        console.log("EVENT INCOMING!!!");
        self.initMarketplace(); //scope error
      }).on('error', console.error);

    },

    async initMarketplace() {
      this.ticketsOnSale = [];
      this.myTickets = [];
      this.items = [];
      const num_tickets = await this.contract.methods.getOnSaleLength().call();
      var uri, data, item, onSale, owner;
      for (let i=0; i<num_tickets; i++) {
        onSale = await this.contract.methods.onSale(i).call();
        owner = await this.contract.methods.owners(i).call();
        if (onSale && owner != this.account) this.ticketsOnSale.push(i);
        if (owner == this.account) this.myTickets.push(i);
        uri = await this.contract.methods.tokenURI(i).call();
        try {
          data = await axios.get(uri);
          item = data.data;
          item.ticket_id = i;
          item.on_sale = await this.contract.methods.onSale(i).call();
          console.log(item);
          this.items.push(item);
        } catch (error) {
          console.log(error);
        }
      }
    },

    async createTicket(price, seat, category) {
      let metadata = {"seat_number":seat, "ticket_category":category, "ticket_value":price};
      console.log(JSON.stringify(metadata));
      let result = await ipfs.add(JSON.stringify(metadata));
      console.log("IPFS hash: ", result.path);
      await this.contract.methods.createTicket(web3.utils.toWei(price,'ether'), result.path).send({from:this.account});
      console.log("Ticket created successfully!");
    },

    async toggleSale(id) {
      await this.contract.methods.toggleSale(id).send({from:this.account});
      console.log("Ticket put on sale!");
    },

    async buyTicket(id) {
      const to_be_paid = await this.contract.methods.ticketPrice(id).call()
      await this.contract.methods.buyTicket(id).send({from:this.account, value:to_be_paid});
      console.log("Ticket bought successfully!");
    },

    async changeTicketPrice(id, price) {
      let uri = await this.contract.methods.tokenURI(id).call();
      var item;
      try {
        let data = await axios.get(uri);
        item = data.data;
        item.ticket_value = price;
        console.log(item);
      } catch (error) {
        console.log(error);
      }
      let result = await ipfs.add(JSON.stringify(item));
      console.log("IPFS hash: ", result.path);
      await this.contract.methods.changeTicketPrice(id, web3.utils.toWei(price,'ether'), result.path).send({from:this.account});
      console.log("Ticket price changed successfully!");
    }

  }
}
</script>
